/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_quantra_LGInterface_LGDictionary */

#ifndef _Included_com_ibm_quantra_LGInterface_LGDictionary
#define _Included_com_ibm_quantra_LGInterface_LGDictionary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_quantra_LGInterface_LGDictionary
 * Method:    dictionaryCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGDictionary_dictionaryCreate
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_ibm_quantra_LGInterface_LGDictionary
 * Method:    dictionaryDelete
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGDictionary_dictionaryDelete
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGDictionary
 * Method:    dictionaryGetMaxCost
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGDictionary_dictionaryGetMaxCost
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
