/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_quantra_LGInterface_LGSentence */

#ifndef _Included_com_ibm_quantra_LGInterface_LGSentence
#define _Included_com_ibm_quantra_LGInterface_LGSentence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_quantra_LGInterface_LGSentence
 * Method:    sentenceCreate
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGSentence_sentenceCreate
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGSentence
 * Method:    sentenceDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGSentence_sentenceDelete
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGSentence
 * Method:    sentenceParse
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGSentence_sentenceParse
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGSentence
 * Method:    sentenceLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGSentence_sentenceLength
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGSentence
 * Method:    sentenceGetWord
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_quantra_LGInterface_LGSentence_sentenceGetWord
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGSentence
 * Method:    sentenceNullCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGSentence_sentenceNullCount
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGSentence
 * Method:    sentenceNumLinkagesFound
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGSentence_sentenceNumLinkagesFound
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGSentence
 * Method:    sentenceNumValidLinkages
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGSentence_sentenceNumValidLinkages
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGSentence
 * Method:    sentenceNumLinkagesPostProcessed
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGSentence_sentenceNumLinkagesPostProcessed
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGSentence
 * Method:    sentenceNumViolations
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGSentence_sentenceNumViolations
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGSentence
 * Method:    sentenceDisjunctCost
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGSentence_sentenceDisjunctCost
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
