/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_quantra_LGInterface_LGParseOptions */

#ifndef _Included_com_ibm_quantra_LGInterface_LGParseOptions
#define _Included_com_ibm_quantra_LGInterface_LGParseOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsDelete
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsDelete
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetVerbosity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetVerbosity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetVerbosity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetVerbosity
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetLinkageLimit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetLinkageLimit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetLinkageLimit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetLinkageLimit
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetDisjunctCost
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetDisjunctCost
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetDisjunctCost
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetDisjunctCost
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetMinNullCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetMinNullCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetMinNullCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetMinNullCount
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetMaxNullCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetMaxNullCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetMaxNullCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetMaxNullCount
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetNullBlock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetNullBlock
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetNullBlock
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetNullBlock
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetShortLength
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetShortLength
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetShortLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetShortLength
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetIslandsOk
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetIslandsOk
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetIslandsOk
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetIslandsOk
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetMaxParseTime
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetMaxParseTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetMaxParseTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetMaxParseTime
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetMaxMemory
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetMaxMemory
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetMaxMemory
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetMaxMemory
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsTimerExpired
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsTimerExpired
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsMemoryExhausted
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsMemoryExhausted
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsResourcesExhausted
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsResourcesExhausted
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsResetResources
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsResetResources
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetCostModelType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetCostModelType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetCostModelType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetCostModelType
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetScreenWidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetScreenWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetScreenWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetScreenWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetAllowNull
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetAllowNull
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetAllowNull
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetAllowNull
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetDisplayWalls
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetDisplayWalls
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetDisplayWalls
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetDisplayWalls
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsSetAllShortConnectors
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsSetAllShortConnectors
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGParseOptions
 * Method:    parseOptionsGetAllShortConnectors
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGParseOptions_parseOptionsGetAllShortConnectors
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
