/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_quantra_LGInterface_LGLinkage */

#ifndef _Included_com_ibm_quantra_LGInterface_LGLinkage
#define _Included_com_ibm_quantra_LGInterface_LGLinkage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageCreate
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageCreate
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageDelete
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetNumSublinkages
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetNumSublinkages
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageSetCurrentSublinkage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageSetCurrentSublinkage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageComputeUnion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageComputeUnion
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetNumWords
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetNumWords
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetNumLinks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetNumLinks
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetLinkLength
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetLinkLength
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetLinkLword
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetLinkLword
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetLinkRword
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetLinkRword
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkagePrintDiagram
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkagePrintDiagram
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkagePrintPostscript
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkagePrintPostscript
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkagePrintLinksAndDomains
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkagePrintLinksAndDomains
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetLinkLabel
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetLinkLabel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetLinkLlabel
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetLinkLlabel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetLinkRlabel
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetLinkRlabel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetLinkNumDomains
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetLinkNumDomains
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetLinkDomainNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetLinkDomainNames
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetViolationName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetViolationName
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetWords
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetWords
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageGetWord
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageGetWord
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageUnusedWordCost
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageUnusedWordCost
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageDisjunctCost
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageDisjunctCost
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageAndCost
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageAndCost
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGLinkage
 * Method:    linkageLinkCost
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGLinkage_linkageLinkCost
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
