/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_quantra_LGInterface_LGConstituent */

#ifndef _Included_com_ibm_quantra_LGInterface_LGConstituent
#define _Included_com_ibm_quantra_LGInterface_LGConstituent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_quantra_LGInterface_LGConstituent
 * Method:    linkageConstituentTree
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGConstituent_linkageConstituentTree
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_quantra_LGInterface_LGConstituent
 * Method:    linkageFreeConstituentTree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGConstituent_linkageFreeConstituentTree
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGConstituent
 * Method:    linkagePrintConstituentTree
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_quantra_LGInterface_LGConstituent_linkagePrintConstituentTree
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
