/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_quantra_LGInterface_LGPostProcessor */

#ifndef _Included_com_ibm_quantra_LGInterface_LGPostProcessor
#define _Included_com_ibm_quantra_LGInterface_LGPostProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_quantra_LGInterface_LGPostProcessor
 * Method:    postProcessOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_quantra_LGInterface_LGPostProcessor_postProcessOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ibm_quantra_LGInterface_LGPostProcessor
 * Method:    postProcessClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGPostProcessor_postProcessClose
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_quantra_LGInterface_LGPostProcessor
 * Method:    linkagePostProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_quantra_LGInterface_LGPostProcessor_linkagePostProcess
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
